apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: borealis-prod-eu
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 2
  template:
    metadata:
    labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: k8s.gcr.io/hpa-example
#          image: deis/hpa-example
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
