name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
outputs:
  deployment-text:
    description: wow
    value: ${{steps.deployment}}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - name: Deployment
      id: deployment

      uses: armory/cli-deploy-action@main
      with:
          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"  # "61ihoLa6dkk5SRwAy232H0TJk1xTBbK6"
          clientSecret: "${{ secrets.CDAAS_CLIENT_SECRET }}" #Client secret that you created in the Armory Cloud Console that has been encrypted with GitHub's encrypted secrets.
          path-to-file: "/deploy-automated-2-env.yml" # Path to the deployment file. For more information, see the Create a deployment file section.


#jobs:
#  build:
#    name: deploy from main
#
#    outputs:
#      deployment-text:
#        description: wow
#        value: ${{steps.deployment}}
#    steps:
#
#      - name: Deployment
#        id: deployment
#
#        uses: armory/cli-deploy-action@main
#        with:
#          clientId: "${{ secrets.CDAAS_CLIENT_ID }}"  # "61ihoLa6dkk5SRwAy232H0TJk1xTBbK6"
#          clientSecret:  "${{ secrets.CDAAS_CLIENT_SECRET }}" #Client secret that you created in the Armory Cloud Console that has been encrypted with GitHub's encrypted secrets.
#          path-to-file: "/deploy-automated-2-env.yml" # Path to the deployment file. For more information, see the Create a deployment file section.
##      - name: script test
##        run: echo "testing echo"
##        shell: bash
##      - name: script
##        run: echo "${{ steps.deployment.outputs.deployment-link }} | grep ID"
##        shell: bash
